//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZacamoMvc.AddressServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddressServiceReference.IAddressService")]
    public interface IAddressService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/AddAddress", ReplyAction="http://tempuri.org/IAddressService/AddAddressResponse")]
        int AddAddress(Entities.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/AddAddress", ReplyAction="http://tempuri.org/IAddressService/AddAddressResponse")]
        System.Threading.Tasks.Task<int> AddAddressAsync(Entities.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/CheckAddress", ReplyAction="http://tempuri.org/IAddressService/CheckAddressResponse")]
        int CheckAddress(Entities.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/CheckAddress", ReplyAction="http://tempuri.org/IAddressService/CheckAddressResponse")]
        System.Threading.Tasks.Task<int> CheckAddressAsync(Entities.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/GetAddressById", ReplyAction="http://tempuri.org/IAddressService/GetAddressByIdResponse")]
        Entities.Address GetAddressById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/GetAddressById", ReplyAction="http://tempuri.org/IAddressService/GetAddressByIdResponse")]
        System.Threading.Tasks.Task<Entities.Address> GetAddressByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddressServiceChannel : ZacamoMvc.AddressServiceReference.IAddressService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressServiceClient : System.ServiceModel.ClientBase<ZacamoMvc.AddressServiceReference.IAddressService>, ZacamoMvc.AddressServiceReference.IAddressService {
        
        public AddressServiceClient() {
        }
        
        public AddressServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddAddress(Entities.Address address) {
            return base.Channel.AddAddress(address);
        }
        
        public System.Threading.Tasks.Task<int> AddAddressAsync(Entities.Address address) {
            return base.Channel.AddAddressAsync(address);
        }
        
        public int CheckAddress(Entities.Address address) {
            return base.Channel.CheckAddress(address);
        }
        
        public System.Threading.Tasks.Task<int> CheckAddressAsync(Entities.Address address) {
            return base.Channel.CheckAddressAsync(address);
        }
        
        public Entities.Address GetAddressById(int id) {
            return base.Channel.GetAddressById(id);
        }
        
        public System.Threading.Tasks.Task<Entities.Address> GetAddressByIdAsync(int id) {
            return base.Channel.GetAddressByIdAsync(id);
        }
    }
}
